In [1]:
import numpy as np

In [2]:
random_number = np.random.randint(0, 10)
print(random_number)

5


In [3]:
my_list = ['spam', 3, 9.5, 'eggs', ['sub list', 3], int]
my_list.append('foo')
my_list[0] = 999
print(my_list)

[999, 3, 9.5, 'eggs', ['sub list', 3], <class 'int'>, 'foo']


In [4]:
my_arr = np.array([1, 2, 3, 4, 5, 6])
print(my_arr)
print(my_arr[3])  

[1 2 3 4 5 6]
4


In [5]:
matrix_2x2 = np.array([[1, 0], [0, 1]])
print(matrix_2x2) 

[[1 0]
 [0 1]]


In [6]:
my_arr = np.array([1, 2, 3, 4, 5, 6])
my_arr2 = np.array([1.5, 1.67, 8.99])
my_arr3 = np.array(['spam', 'eggs', 'foo', 'bar'])
print(my_arr2) 

[1.5  1.67 8.99]


In [7]:
my_arr = np.arange(10)
print(my_arr)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
my_arr = np.empty(10, dtype=np.int64)
print(my_arr)
print(my_arr.dtype)

[     94198377364365                   0                   0
 7005683683222185060 7365134955177981241 7161961665417786165
 3487527945845749303 3546079365856047415 7147838455017583923
 3486975119126966838]
int64


In [9]:
my_arr = np.zeros(10, dtype=np.int64)
print(my_arr)
print(my_arr.dtype)

[0 0 0 0 0 0 0 0 0 0]
int64


In [10]:
my_arr = np.arange(5000)
my_arr.shape

(5000,)

In [11]:
python_list = list(range(1000000))
numpy_array = np.arange(1000000)

In [12]:
%timeit sum(python_list)

4.62 ms ± 18.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [13]:
%timeit np.sum(numpy_array)

403 µs ± 938 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [14]:
x = np.array([10, 20, 30, 40])
y = np.array([10, 10, 10, 10])

z = x - y 

print(z)

[ 0 10 20 30]


In [15]:
x = np.array([10, 20, 30, 40], dtype=np.int64)
y = x + 5
z = y ** 2

print(z)

[ 225  625 1225 2025]


In [16]:
short_sequence = np.arange(10, dtype=np.int16)
print(short_sequence)
short_sequence[4] = 444
print(short_sequence)

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3 444   5   6   7   8   9]


In [17]:
integer_matrix = np.arange(5, dtype=np.int64)
floating_point_number = 22.667
integer_matrix[0] = floating_point_number

print(integer_matrix)

[22  1  2  3  4]


In [18]:
complete_matrix = np.array([10, 11, 12, 13, 14, 15])

In [19]:
slice_matrix = complete_matrix[3:5]

print('complete matrix: {0}'.format(complete_matrix))
print('slice of matrix: {0}'.format(slice_matrix))

complete matrix: [10 11 12 13 14 15]
slice of matrix: [13 14]


In [20]:
complete_matrix = np.arange(10)
print(complete_matrix)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
slice_matrix = complete_matrix[6:]

print('original matrix: {0}'.format(complete_matrix))
print('slice of matrix: {0}'.format(slice_matrix)) 

original matrix: [0 1 2 3 4 5 6 7 8 9]
slice of matrix: [6 7 8 9]


In [22]:
slice_matrix = complete_matrix[-4:]

print('complete matrix: {0}'.format(complete_matrix))
print('slice of matrix: {0}'.format(slice_matrix))

complete matrix: [0 1 2 3 4 5 6 7 8 9]
slice of matrix: [6 7 8 9]


In [23]:
complete_matrix = np.arange(10, 20)

slice_matrix = complete_matrix[0:3]  #could also omit the start of 0

print('original matrix: {0}'.format(complete_matrix))
print('slice of matrix: {0}'.format(slice_matrix))

original matrix: [10 11 12 13 14 15 16 17 18 19]
slice of matrix: [10 11 12]


In [24]:
slice_matrix = complete_matrix[0:-7]
 
print('original matrix: {0}'.format(complete_matrix))
print('slice of matrix: {0}'.format(slice_matrix))

original matrix: [10 11 12 13 14 15 16 17 18 19]
slice of matrix: [10 11 12]


In [25]:
indexes = [2, 4, 6]
sub_matrix = complete_matrix[indexes]

print('original matrix: {0}'.format(complete_matrix))
print('sub matrix: {0}'.format(sub_matrix))


original matrix: [10 11 12 13 14 15 16 17 18 19]
sub matrix: [12 14 16]


In [26]:
complete_matrix = np.arange(10, 20)
slice_matrix = complete_matrix[0:3] 

print(slice_matrix)
slice_matrix[0] = 999
print(slice_matrix)

[10 11 12]
[999  11  12]


In [27]:
print(complete_matrix)

[999  11  12  13  14  15  16  17  18  19]


In [28]:
file_name = 'data/minor_illness_ed_attends.csv'
ed_data = np.genfromtxt(file_name, skip_header=1, delimiter=',')

In [29]:
print(ed_data.shape)
print(ed_data.dtype)

(74,)
float64


In [30]:
def ed_summary_statistics(data):
    """
    Returns mean, stdev and 5/95 percentiles of ed data
    
    Keyword arguments:
    data -- 1d numpy.ndarray containing data to analyse
    """
    mean = data.mean()
    std = data.std()
    min_attends = data.min()
    max_attends = data.max() 
    per_95 = np.percentile(data, 95)
    
    return mean, std, min_attends, max_attends, per_95

In [31]:
def print_summary_stats(mean, std, minimum, maximum, per_95):
    """
    Prints summary statistics in formatted text.
    
    Keyword arguments:
    mean -- mean average
    std -- standard deviation 
    minimum -- min value
    maximum -- max value
    """
    print('Mean:\t{0:0.2f}'.format(mean))
    print('Stdev:\t{0:0.2f}'.format(std))
    print('Min:\t{0:0.2f}'.format(minimum))
    print('Max:\t{0:0.2f}'.format(maximum))
    print('95th:\t{0:0.2f}'.format(per_95))
    

In [32]:
mean, std, min_attends, max_attends, per_95 = ed_summary_statistics(ed_data)

print_summary_stats(mean, std, min_attends, max_attends, per_95)

Mean:	2.92
Stdev:	0.71
Min:	1.62
Max:	5.11
95th:	3.99


In [33]:
stats = ed_summary_statistics(ed_data)
type(stats)

tuple

In [34]:
mybins = np.linspace(start=1.5, stop = 5.5, num=9)
freq, bins = np.histogram(ed_data, bins=mybins, density=False)
print(bins)
print(freq)

[1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5]
[ 7 19 18 13 14  2  0  1]


In [35]:
def sub_group_analysis(data, group_name):
    mean, std, min_attends, max_attends, per_95 = ed_summary_statistics(data)
    print('***{0}'.format(group_name))
    print_summary_stats(mean, std, min_attends, max_attends, per_95)

week = 10  # the week the intervention begins
sub_group_analysis(ed_data[0:week], 'before')
sub_group_analysis(ed_data[week:], 'after')

***before
Mean:	3.12
Stdev:	0.56
Min:	2.12
Max:	3.99
95th:	3.82
***after
Mean:	2.89
Stdev:	0.72
Min:	1.62
Max:	5.11
95th:	3.97


In [36]:
stats = ed_summary_statistics(ed_data)

#95th percentile is contained in index 4
per_95 = stats[4]

extreme_week = np.where(ed_data >= per_95)

print(extreme_week)

(array([10, 41, 65]),)
